// utils/constants.js
const CLASS_CONSTANTS = {
  SEMESTERS: ["Fall", "Spring", "Summer", "Winter"],
  ENROLLMENT_STATUS: ["active", "dropped", "completed"],
  ENROLLMENT_SOURCES: ["enrollment_key", "teacher_invite", "admin_add"],
  AI_STRICTNESS: ["lenient", "moderate", "strict"],
  FEEDBACK_DETAIL: ["brief", "detailed"],

  LIMITS: {
    CLASS_NAME_MIN: 3,
    CLASS_NAME_MAX: 100,
    DESCRIPTION_MAX: 500,
    SUBJECT_MAX: 50,
    MAX_STUDENTS_MIN: 1,
    MAX_STUDENTS_MAX: 200,
    MAX_STUDENTS_DEFAULT: 50,
    ENROLLMENT_KEY_EXPIRY_HOURS: 24,
    GRADE_MIN: 0,
    GRADE_MAX: 100,
    ATTENDANCE_MIN: 0,
    ATTENDANCE_MAX: 100,
  },

  PATTERNS: {
    CLASS_CODE: /^\d{3}$/,
    ENROLLMENT_KEY: /^\d{6}$/,
    ACADEMIC_YEAR: /^\d{4}-\d{4}$/,
  },
};

const ERROR_CODES = {
  // Class errors
  CLASS_NOT_FOUND: "CLASS_NOT_FOUND",
  CLASS_INACTIVE: "CLASS_INACTIVE",
  CLASS_FULL: "CLASS_FULL",
  CODE_GENERATION_FAILED: "CODE_GENERATION_FAILED",
  KEY_GENERATION_FAILED: "KEY_GENERATION_FAILED",

  // Enrollment errors
  ALREADY_ENROLLED: "ALREADY_ENROLLED",
  ENROLLMENT_NOT_FOUND: "ENROLLMENT_NOT_FOUND",
  INVALID_ENROLLMENT_KEY: "INVALID_ENROLLMENT_KEY",
  ENROLLMENT_KEY_EXPIRED: "ENROLLMENT_KEY_EXPIRED",
  TEACHER_SELF_ENROLLMENT: "TEACHER_SELF_ENROLLMENT",

  // Permission errors
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
};

module.exports = { CLASS_CONSTANTS, ERROR_CODES };
